#!/usr/bin/env bash
# Refresh ONE user's data on staging from a production snapshot.
#
#   npm run db:sync-staging                        # default user (see EMAIL)
#   EMAIL=someone@example.com npm run db:sync-staging
#   npm run db:sync-staging -- --yes               # skip the confirmation
#
# Staging is a week-stale clone of production, so its dashboard drifts out of
# date. This re-syncs a single user's rows and leaves every other user alone.
#
# Why only one user: prod has 17 usuarios. Copying all of them means replicating
# other people's real financial records into a second system, and it does not
# even work -- public.usuarios.user_id is FK'd to auth.users, and staging's auth
# ids differ from prod's, so the rows either violate the FK or land invisible
# behind RLS. This script sidesteps both by resolving usuario_id ON STAGING, by
# email, at load time (see the generated subselects).
#
# Things that do NOT work, learned the hard way -- do not "simplify" into them:
#
#   * `supabase db dump` against staging. Staging runs Postgres 17.6 while the
#     CLI pins pg_dump 15.8 (prod is 15), and pg_dump refuses a newer server.
#     Reading PROD is fine, which is all this script needs.
#   * `supabase seed --linked`. Its only subcommand is `buckets`; it seeds
#     storage buckets from config.toml and never runs seed.sql against a remote.
#   * `psql` against staging. The Homebrew client here is 14.x, and you would
#     have to hand-carry the DB password. `supabase db push` needs neither -- it
#     provisions a temporary login role over the management API.
#
# So the load path is: generate SQL -> drop it in as a throwaway migration ->
# `db push` -> delete the file -> repair the history. The migration file holds
# real financial data, so it is removed on EXIT no matter how this script ends.
set -euo pipefail

PROD_REF="vvzadoagclwzjuhgbwgf"
STAGING_REF="tswabgfnkwbcbwammnbi"
EMAIL="${EMAIL:-simon.echeverri2003@gmail.com}"
BACKUP_ROOT="${BACKUP_ROOT:-$HOME/backups/finanzas}"

ASSUME_YES=""
[[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && ASSUME_YES=1

cd "$(dirname "$0")/.."

VERSION="$(date +%Y%m%d%H%M%S)"
MIGRATION="supabase/migrations/${VERSION}_staging_data_sync.sql"
DUMP_DIR="$BACKUP_ROOT/staging-sync-$(date +%Y%m%d-%H%M%S)"
PUSHED=""

cleanup() {
  rm -f "$MIGRATION"
  # Only repair history if the push actually applied it; repairing a version
  # that was never applied just writes a spurious row.
  if [[ -n "$PUSHED" ]]; then
    supabase migration repair --status reverted "$VERSION" >/dev/null 2>&1 || \
      echo "!! Could not repair history for $VERSION -- run it by hand." >&2
  fi
  rm -rf supabase/.temp   # a live link breaks local `supabase start`
}
trap cleanup EXIT

echo "==> Dumping production data (read-only, no link needed)"
mkdir -p "$DUMP_DIR"
supabase db dump --project-ref "$PROD_REF" --data-only --schema public \
  -f "$DUMP_DIR/prod-data.sql"

echo "==> Generating staging SQL for $EMAIL"
DUMP="$DUMP_DIR/prod-data.sql" TARGET_EMAIL="$EMAIL" OUT="$DUMP_DIR/staging-sync.sql" \
python3 <<'PY'
import os, re, sys

dump  = open(os.environ["DUMP"]).read()
email = os.environ["TARGET_EMAIL"]
sub   = "(select id from public.usuarios where email = '%s')" % email

def table(name):
    m = re.search(r'INSERT INTO "public"\."%s" \(([^)]*)\) VALUES\s*(.*?);\s*\n' % name,
                  dump, re.S)
    if not m:
        return None, []
    cols = [c.strip().strip('"') for c in m.group(1).split(",")]
    rows = re.findall(r"\(((?:[^()']|'(?:[^']|'')*')*)\)", m.group(2))
    return cols, rows

def fields(row):
    # Split on top-level commas only; quoted text may contain commas, parens
    # and '' escapes.
    return [x.strip() for x in re.split(r",(?=(?:[^']*'(?:[^']|'')*')*[^']*$)", row)]

# Resolve the prod-side usuarios.id for this email.
ucols, urows = table("usuarios")
if not ucols:
    sys.exit("No usuarios rows in the dump -- is the dump empty?")
ei, ii = ucols.index("email"), ucols.index("id")
prod_uid = next((fields(r)[ii].strip("'") for r in urows
                 if fields(r)[ei].strip("'") == email), None)
if prod_uid is None:
    sys.exit("No usuarios row in PROD for %s" % email)

out = ["""-- Staging data sync: production rows for %s only.
-- Generated by scripts/sync-staging-from-prod.sh. Not for committing: this
-- file holds real financial data and is deleted right after `db push`.
--
-- usuario_id is resolved on STAGING by email, because staging's usuarios.id
-- is not prod's. Everything else is copied verbatim, ids included.

do $$
begin
  if not exists (select 1 from public.usuarios where email = '%s') then
    raise exception 'No usuarios row on staging for %s. Sign in to staging once, then re-run.';
  end if;
end $$;

-- Only this user's rows, children first.
delete from public.movimiento_tags
 where movimiento_id in (select id from public.movimientos where usuario_id = %s)
    or tag_id in (select id from public.tags where usuario_id = %s);
delete from public.movimientos       where usuario_id = %s;
delete from public.pagos_recurrentes where usuario_id = %s;
delete from public.metas             where usuario_id = %s;
delete from public.tags              where usuario_id = %s;
delete from public.tipo_movimiento   where usuario_id = %s;
""" % (email, email, email, sub, sub, sub, sub, sub, sub, sub)]

counts, my_mov_ids = {}, set()

# Order matters: movimientos FK to tipo_movimiento and pagos_recurrentes.
for name in ("tipo_movimiento", "tags", "pagos_recurrentes", "metas", "movimientos"):
    cols, rows = table(name)
    if not cols:
        counts[name] = 0
        continue
    ui = cols.index("usuario_id")
    mine = [fields(r) for r in rows if fields(r)[ui].strip("'") == prod_uid]
    counts[name] = len(mine)
    if name == "movimientos":
        my_mov_ids = {r[cols.index("id")].strip("'") for r in mine}
    if not mine:
        continue
    out.append("\ninsert into public.%s (%s) values" % (name, ", ".join(cols)))
    vals = []
    for f in mine:
        f = list(f)
        f[ui] = sub
        vals.append("  (" + ", ".join(f) + ")")
    out.append(",\n".join(vals) + ";")

# The junction table hangs off movimientos, not usuarios.
cols, rows = table("movimiento_tags")
mine = [fields(r) for r in rows
        if fields(r)[cols.index("movimiento_id")].strip("'") in my_mov_ids] if cols else []
counts["movimiento_tags"] = len(mine)
if mine:
    out.append("\ninsert into public.movimiento_tags (%s) values" % ", ".join(cols))
    out.append(",\n".join("  (" + ", ".join(f) + ")" for f in mine) + ";")

open(os.environ["OUT"], "w").write("\n".join(out) + "\n")
for k, v in counts.items():
    print("    %-20s %5d" % (k, v))
PY

echo "==> Linking to STAGING"
supabase link --project-ref "$STAGING_REF" --yes >/dev/null

# Hard gate. This SQL opens with DELETEs; pointed at prod it would destroy real
# data. supabase/.temp/project-ref is what `db push` actually targets, and it
# has historically been left pointing at production.
REF="$(cat supabase/.temp/project-ref)"
if [[ "$REF" != "$STAGING_REF" ]]; then
  echo "ABORT: linked ref is '$REF', expected staging '$STAGING_REF'." >&2
  exit 1
fi
echo "    ref gate passed: $REF"

if [[ -z "$ASSUME_YES" ]]; then
  echo ""
  echo "About to REPLACE $EMAIL's rows on staging ($STAGING_REF)."
  read -r -p "Type 'yes' to continue: " reply
  [[ "$reply" == "yes" ]] || { echo "Aborted."; exit 1; }
fi

echo "==> Pushing to staging"
cp "$DUMP_DIR/staging-sync.sql" "$MIGRATION"
supabase db push --yes
PUSHED=1

echo ""
echo "==> Done. Dump kept at: $DUMP_DIR"
echo "    Verify by loading the staging dashboard -- row counts alone do not"
echo "    prove RLS matches your staging login."
